name: Guojin Chen @ CUHK-CSE
url: https://dekura.github.io
description: Home page of Guojin Chen @ CUHK-CSE. He is now a research assistant at The Chinese University of Hong Kong (CUHK-CSE) and broadly study foundational topics and applications in machine/deep learning in VLSI and optimization, including reinforcement learning, computer vision.
destination: ./_site
twitter: dekura11
lsi: false
port: 4000
markdown: kramdown
future: true
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
permalink: pretty
#seo
tagline: Guojin Chen's Awesome Site | Home site for Guojin Chen CUHK
#paginate: 5
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .travis.yml
  - validate.rb
  - README.md
  - Gemfile
  - Gemfile.lock
  - bower_components
  - update-vendor-deps.sh
  - vendor/bundle
  - vendor/bower.json
